name: Deploy to AWS

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    name: Build for Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install dependencies"
        run: |
          # Update "pip" to the newest version
          python -m pip install --upgrade pip

          # Install flake8 and pytest
          pip install flake8 pytest

          # If there is a "requirements.txt" file, then install everything from it, otherwise do nothing else.
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  deploy_to_aws:
    name: Deploy function to AWS Lambda
    strategy:
      matrix:
        python-version:
          - 3.9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          # Update "pip" to the newest version
          python -m pip install --upgrade pip
          
          # If there is a "requirements.txt" file, then install everything from it, otherwise do nothing else.
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create zip file
        uses: montudor/action-zip@1.0.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: Default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: slack-free-epic-games
          zip_file: bundle.zip
